import { Router } from 'express'; import bcrypt from 'bcryptjs'; import crypto from 'crypto'; import jwt from 'jsonwebtoken'; import { z } from 'zod'; import { loginSchema, registerSchema } from '@internflow/shared'; import { User } from '../models/User'; import { Profile } from '../models/Profile'; import { asyncHandler } from '../utils/asyncHandler'; import { hashToken, signAccessToken, signRefreshToken } from '../utils/tokens'; import { env } from '../config/env'; import { sendEmail } from '../services/email';
export const authRouter = Router();
function publicUser(user:any){ return {id:user._id,email:user.email,roles:user.roles,emailVerifiedAt:user.emailVerifiedAt}; }
async function issueVerification(user:any){ const token=crypto.randomBytes(32).toString('hex'); user.emailVerificationTokenHash=hashToken(token); await user.save(); await sendEmail(user.email,'Verify your InternFlow email',`Verify your email: ${env.APP_URL}/verify-email?token=${token}`); return token; }
authRouter.post('/register', asyncHandler(async (req,res)=>{ const input=registerSchema.parse(req.body); const exists=await User.exists({email:input.email}); if(exists) return res.status(409).json({message:'Email already registered'}); const user=await User.create({email:input.email,passwordHash:await bcrypt.hash(input.password,12),roles:[input.role]}); await Profile.create({userId:user._id,fullName:input.fullName,completenessScore:20}); await issueVerification(user); const tokenId=crypto.randomUUID(); const refreshToken=signRefreshToken(String(user._id),tokenId); user.sessions.push({refreshTokenHash:hashToken(refreshToken),userAgent:req.get('user-agent'),ip:req.ip,expiresAt:new Date(Date.now()+30*864e5)} as any); await user.save(); res.status(201).json({accessToken:signAccessToken(String(user._id),user.roles[0]),refreshToken,user:publicUser(user)}); }));
authRouter.post('/login', asyncHandler(async (req,res)=>{ const input=loginSchema.parse(req.body); const user=await User.findOne({email:input.email,status:'active'}); if(!user || !(await bcrypt.compare(input.password,user.passwordHash))) return res.status(401).json({message:'Invalid credentials'}); const tokenId=crypto.randomUUID(); const refreshToken=signRefreshToken(String(user._id),tokenId); user.sessions.push({refreshTokenHash:hashToken(refreshToken),userAgent:req.get('user-agent'),ip:req.ip,expiresAt:new Date(Date.now()+30*864e5)} as any); await user.save(); res.json({accessToken:signAccessToken(String(user._id),user.roles[0]),refreshToken,user:publicUser(user)}); }));
authRouter.post('/refresh', asyncHandler(async(req,res)=>{ const {refreshToken}=req.body; if(!refreshToken) return res.status(400).json({message:'refreshToken required'}); const payload=jwt.verify(refreshToken,env.JWT_REFRESH_SECRET) as {sub:string}; const tokenHash=hashToken(refreshToken); const user=await User.findOne({_id:payload.sub,'sessions.refreshTokenHash':tokenHash,'sessions.revokedAt':{$exists:false}}); if(!user) return res.status(401).json({message:'Invalid refresh token'}); res.json({accessToken:signAccessToken(String(user._id),user.roles[0])}); }));
authRouter.post('/verify-email', asyncHandler(async(req,res)=>{ const token=z.object({token:z.string().min(16)}).parse(req.body).token; const user=await User.findOne({emailVerificationTokenHash:hashToken(token)}); if(!user) return res.status(400).json({message:'Invalid verification token'}); user.emailVerifiedAt=new Date(); user.emailVerificationTokenHash=undefined; await user.save(); res.json({message:'Email verified'}); }));
authRouter.post('/forgot-password', asyncHandler(async(req,res)=>{ const {email}=z.object({email:z.string().email()}).parse(req.body); const user=await User.findOne({email}); if(user){ const token=crypto.randomBytes(32).toString('hex'); user.passwordResetTokenHash=hashToken(token); user.passwordResetExpiresAt=new Date(Date.now()+60*60*1000); await user.save(); await sendEmail(user.email,'Reset your InternFlow password',`Reset your password: ${env.APP_URL}/reset-password?token=${token}`); } res.json({message:'If the email exists, a reset link has been sent'}); }));
authRouter.post('/reset-password', asyncHandler(async(req,res)=>{ const {token,password}=z.object({token:z.string().min(16),password:z.string().min(8)}).parse(req.body); const user=await User.findOne({passwordResetTokenHash:hashToken(token),passwordResetExpiresAt:{$gt:new Date()}}); if(!user) return res.status(400).json({message:'Invalid or expired reset token'}); user.passwordHash=await bcrypt.hash(password,12); user.passwordResetTokenHash=undefined; user.passwordResetExpiresAt=undefined; user.sessions=[] as any; await user.save(); res.json({message:'Password reset successful'}); }));
