import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { api, clearAuth, storeAuth, type AuthPayload, type AuthUser } from './lib/api';

const statuses = ['saved', 'applied', 'assessment', 'interview', 'offer', 'rejected', 'joined'];
const workModes = ['remote', 'hybrid', 'onsite'];

type Internship = { _id: string; title: string; company: string; description: string; skills?: string[]; requirements?: string[]; location?: string; workMode?: string; stipendMin?: number; stipendMax?: number; currency?: string; sourceUrl?: string; matchScore?: number; deadline?: string };
type Application = { _id: string; title: string; company: string; status: string; notes?: string; sourceUrl?: string; updatedAt?: string };
type Notice = { type: 'error' | 'success' | 'info'; text: string } | null;

function App() {
  const [token, setToken] = useState(localStorage.getItem('accessToken'));
  const [user, setUser] = useState<AuthUser | null>(() => JSON.parse(localStorage.getItem('currentUser') || 'null'));
  const [view, setView] = useState('dashboard');
  const role = user?.roles?.includes('recruiter') ? 'recruiter' : 'student';

  function onAuth(payload: AuthPayload) {
    storeAuth(payload);
    setToken(payload.accessToken);
    setUser(payload.user ?? null);
  }

  if (!token) return <Auth onAuth={onAuth} />;
  const nav = role === 'recruiter' ? ['dashboard', 'post internship', 'applications', 'profile'] : ['dashboard', 'discover', 'resume', 'tracker', 'profile'];
  return <div className="shell"><aside><h2>InternFlow</h2><p className="muted">{role} portal</p>{nav.map((v) => <button key={v} className={view === v ? 'active' : ''} onClick={() => setView(v)}>{v}</button>)}<button onClick={() => { clearAuth(); setToken(null); setUser(null); }}>logout</button></aside><main>{view === 'dashboard' && (role === 'recruiter' ? <RecruiterDashboard /> : <StudentDashboard />)}{view === 'discover' && <Discover />}{view === 'resume' && <Resume />}{view === 'tracker' && <Tracker />}{view === 'post internship' && <PostInternship />}{view === 'applications' && <RecruiterDashboard />}{view === 'profile' && <Profile />}</main></div>;
}

function Auth({ onAuth }: { onAuth: (payload: AuthPayload) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [role, setRole] = useState<'student' | 'recruiter'>('student');
  const [email, setEmail] = useState('student@example.com');
  const [password, setPassword] = useState('password123');
  const [fullName, setFullName] = useState('Demo Student');
  const [notice, setNotice] = useState<Notice>(null);
  async function submit(e: React.FormEvent) { e.preventDefault(); setNotice(null); try { const body = mode === 'register' ? { email, password, fullName, role } : { email, password }; const { data } = await api.post<AuthPayload>(`/auth/${mode}`, body); onAuth(data); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Authentication failed' }); } }
  return <div className="auth"><form onSubmit={submit}><h1>{mode === 'login' ? 'Welcome back' : 'Create account'}</h1><NoticeBox notice={notice} />{mode === 'register' && <><input required value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="Full name" /><label>Account type<select value={role} onChange={(e) => setRole(e.target.value as any)}><option value="student">Student</option><option value="recruiter">Recruiter</option></select></label></>}<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" /><input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" /><button>Continue</button><a onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account?' : 'Have an account?'}</a></form></div>;
}

function StudentDashboard() { const [recs, setRecs] = useState<Internship[]>([]); const [apps, setApps] = useState<Application[]>([]); useEffect(() => { api.get('/recommendations').then((r) => setRecs(r.data)); api.get('/applications').then((r) => setApps(r.data)); }, []); return <><h1>Your career at a glance</h1><div className="cards"><Card k="Top match" v={`${recs[0]?.matchScore ?? 0}%`} /><Card k="Applications" v={apps.length} /><Card k="Interviews" v={apps.filter((a) => a.status === 'interview').length} /></div><h2>Recommended internships</h2><div className="grid">{recs.slice(0, 4).map((i) => <Job key={i._id} job={i} />)}</div></>; }
function RecruiterDashboard() { const [jobs, setJobs] = useState<Internship[]>([]); useEffect(() => { api.get('/internships/mine').then((r) => setJobs(r.data)); }, []); return <><h1>Recruiter dashboard</h1><div className="cards"><Card k="Open roles" v={jobs.length} /><Card k="Remote roles" v={jobs.filter((j) => j.workMode === 'remote').length} /><Card k="Total reach" v="Live" /></div><h2>Your postings</h2><div className="grid">{jobs.map((j) => <Job key={j._id} job={j} recruiter />)}</div></>; }
function Card(p: { k: string; v: string | number }) { return <section className="card metric"><small>{p.k}</small><strong>{p.v}</strong></section>; }

function Discover() { const [jobs, setJobs] = useState<Internship[]>([]); const [q, setQ] = useState(''); const [workMode, setWorkMode] = useState(''); const [skill, setSkill] = useState(''); const params = useMemo(() => ({ q, workMode, skill }), [q, workMode, skill]); useEffect(() => { const id = setTimeout(() => api.get('/internships', { params }).then((r) => setJobs(r.data)), 250); return () => clearTimeout(id); }, [params]); return <><h1>Discover opportunities</h1><div className="filters"><input className="search" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search roles, companies, skills" /><select value={workMode} onChange={(e) => setWorkMode(e.target.value)}><option value="">Any work mode</option>{workModes.map((m) => <option key={m}>{m}</option>)}</select><input value={skill} onChange={(e) => setSkill(e.target.value)} placeholder="Filter skill" /></div><div className="grid">{jobs.map((j) => <Job key={j._id} job={j} />)}</div></>; }
function Job({ job, recruiter = false }: { job: Internship; recruiter?: boolean }) { const [notice, setNotice] = useState<Notice>(null); async function apply(status: string) { try { await api.post('/applications', { internshipId: job._id, company: job.company, title: job.title, sourceUrl: job.sourceUrl, status }); setNotice({ type: 'success', text: status === 'saved' ? 'Saved to tracker' : 'Application tracked' }); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Could not update application' }); } } return <section className="card"><b>{job.title}</b><p>{job.company} · {job.location || 'Remote'} · {job.workMode}</p><p>{job.description}</p><p>{job.skills?.join(', ')}</p>{job.matchScore !== undefined && <strong>{job.matchScore}% match</strong>}<NoticeBox notice={notice} />{!recruiter && <div className="actions"><button onClick={() => apply('saved')}>Save</button><button onClick={() => apply('applied')}>Track applied</button>{job.sourceUrl && <a href={job.sourceUrl} target="_blank" rel="noreferrer">External apply</a>}</div>}</section>; }

function PostInternship() { const [form, setForm] = useState({ title: '', company: '', description: '', skills: '', requirements: '', location: 'Remote', workMode: 'remote', source: 'recruiter', sourceUrl: 'https://example.com/apply', stipendMin: '', stipendMax: '' }); const [notice, setNotice] = useState<Notice>(null); async function submit(e: React.FormEvent) { e.preventDefault(); try { await api.post('/internships', { ...form, skills: split(form.skills), requirements: split(form.requirements), stipendMin: num(form.stipendMin), stipendMax: num(form.stipendMax) }); setNotice({ type: 'success', text: 'Internship posted' }); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Posting failed' }); } } return <><h1>Post internship</h1><form className="panel" onSubmit={submit}><NoticeBox notice={notice} />{['title', 'company', 'location', 'sourceUrl', 'skills', 'requirements', 'stipendMin', 'stipendMax'].map((k) => <input key={k} value={(form as any)[k]} onChange={(e) => setForm({ ...form, [k]: e.target.value })} placeholder={k} />)}<select value={form.workMode} onChange={(e) => setForm({ ...form, workMode: e.target.value })}>{workModes.map((m) => <option key={m}>{m}</option>)}</select><textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Description" /><button>Publish</button></form></>; }
function Resume() { const [file, setFile] = useState<File | null>(null); const [items, setItems] = useState<any[]>([]); const [notice, setNotice] = useState<Notice>(null); useEffect(() => { api.get('/resumes').then((r) => setItems(r.data)); }, []); async function upload() { if (!file) return setNotice({ type: 'error', text: 'Choose a text resume first' }); const fd = new FormData(); fd.append('resume', file); try { const { data } = await api.post('/resumes/upload', fd); setItems([data, ...items]); setNotice({ type: 'success', text: 'Resume analyzed and profile skills updated' }); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Upload failed' }); } } return <><h1>Resume Intelligence</h1><section className="panel"><NoticeBox notice={notice} /><input type="file" accept=".txt,.md,.csv" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><button onClick={upload}>Analyze</button></section>{items.map((r) => <section className="card" key={r._id}><b>{r.originalName}</b><p>Score: {r.analysis?.resumeScore}</p><p>Skills: {r.analysis?.skillMatrix?.map((s: any) => s.name).join(', ')}</p><p>{r.analysis?.recommendations?.join(' ')}</p></section>)}</>; }
function Tracker() { const [apps, setApps] = useState<Application[]>([]); useEffect(() => { api.get('/applications').then((r) => setApps(r.data)); }, []); async function update(id: string, status: string) { const { data } = await api.patch(`/applications/${id}/status`, { status }); setApps(apps.map((a) => a._id === id ? data : a)); } return <><h1>Application Tracker</h1><div className="kanban">{statuses.map((s) => <section key={s}><h3>{s}</h3>{apps.filter((a) => a.status === s).map((a) => <div className="mini" key={a._id}><b>{a.title}</b><p>{a.company}</p><select value={a.status} onChange={(e) => update(a._id, e.target.value)}>{statuses.map((x) => <option key={x}>{x}</option>)}</select></div>)}</section>)}</div></>; }
function Profile() { const [p, setP] = useState<any>({ skills: [], education: [], preferences: { roles: [], locations: [], workModes: [] } }); const [notice, setNotice] = useState<Notice>(null); useEffect(() => { api.get('/profile/me').then((r) => setP(r.data || p)); }, []); async function save() { try { await api.put('/profile/me', p); setNotice({ type: 'success', text: 'Profile saved' }); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Save failed' }); } } return <><h1>Profile</h1><section className="panel"><NoticeBox notice={notice} /><input value={p.fullName || ''} onChange={(e) => setP({ ...p, fullName: e.target.value })} placeholder="Full name" /><input value={p.location || ''} onChange={(e) => setP({ ...p, location: e.target.value })} placeholder="Location" /><textarea value={p.bio || ''} onChange={(e) => setP({ ...p, bio: e.target.value })} placeholder="Bio" /><input defaultValue={p.skills?.map((s: any) => s.name).join(', ')} onBlur={(e) => setP({ ...p, skills: split(e.target.value).map((name) => ({ name, proficiencyLevel: 3, source: 'manual' })) })} placeholder="Skills comma separated" /><input defaultValue={p.preferences?.roles?.join(', ')} onBlur={(e) => setP({ ...p, preferences: { ...p.preferences, roles: split(e.target.value) } })} placeholder="Target roles comma separated" /><button onClick={save}>Save profile</button></section></>; }
function NoticeBox({ notice }: { notice: Notice }) { return notice ? <p className={notice.type}>{notice.text}</p> : null; }
function split(value: string) { return value.split(',').map((x) => x.trim()).filter(Boolean); }
function num(value: string) { return value === '' ? undefined : Number(value); }

createRoot(document.getElementById('root')!).render(<App />);
