import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';import{api}from'./lib/api';
const statuses=['saved','applied','assessment','interview','offer','rejected','joined'];
function App(){const[token,setToken]=useState(localStorage.getItem('accessToken'));const[view,setView]=useState('dashboard');if(!token)return <Auth onAuth={t=>{localStorage.setItem('accessToken',t);setToken(t)}}/>;return <div className="shell"><aside><h2>InternFlow</h2>{['dashboard','discover','resume','tracker','profile'].map(v=><button className={view===v?'active':''}onClick={()=>setView(v)}>{v}</button>)}<button onClick={()=>{localStorage.clear();setToken(null)}}>logout</button></aside><main>{view==='dashboard'&&<Dashboard/>}{view==='discover'&&<Discover/>}{view==='resume'&&<Resume/>}{view==='tracker'&&<Tracker/>}{view==='profile'&&<Profile/>}</main></div>}
function Auth({onAuth}:{onAuth:(t:string)=>void}){const[mode,setMode]=useState('login');const[email,setEmail]=useState('student@example.com');const[password,setPassword]=useState('password123');const[fullName,setFullName]=useState('Demo Student');async function submit(e:any){e.preventDefault();const{data}=await api.post(`/auth/${mode}`,{email,password,fullName});onAuth(data.accessToken)}return <div className="auth"><form onSubmit={submit}><h1>{mode==='login'?'Welcome back':'Create account'}</h1>{mode==='register'&&<input value={fullName}onChange={e=>setFullName(e.target.value)}placeholder="Full name"/>}<input value={email}onChange={e=>setEmail(e.target.value)}placeholder="Email"/><input type="password"value={password}onChange={e=>setPassword(e.target.value)}placeholder="Password"/><button>Continue</button><a onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account?':'Have an account?'}</a></form></div>}
function Dashboard(){const[recs,setRecs]=useState<any[]>([]);useEffect(()=>{api.get('/recommendations').then(r=>setRecs(r.data)).catch(()=>{})},[]);return <><h1>Your career at a glance</h1><div className="cards"><Card k="Career Score" v="82"/><Card k="Applications" v="24"/><Card k="Interviews" v="6"/></div><h2>Top matches</h2><div className="grid">{recs.slice(0,4).map(i=><Job job={i}/>)}</div></>}
function Card(p:any){return <section className="card"><small>{p.k}</small><strong>{p.v}</strong></section>}
function Discover(){const[jobs,setJobs]=useState<any[]>([]);const[q,setQ]=useState('');useEffect(()=>{api.get('/internships',{params:{q}}).then(r=>setJobs(r.data))},[q]);return <><h1>Discover opportunities</h1><input className="search" value={q}onChange={e=>setQ(e.target.value)}placeholder="Search roles, companies, skills"/><div className="grid">{jobs.map(j=><Job job={j}/>)}</div></>}
function Job({job}:any){async function save(){await api.post('/applications',{internshipId:job._id,company:job.company,title:job.title,sourceUrl:job.sourceUrl,status:'saved'})}return <section className="card"><b>{job.title}</b><p>{job.company} · {job.location||'Remote'}</p><p>{job.skills?.join(', ')}</p><strong>{job.matchScore}% match</strong><button onClick={save}>Save</button><a href={job.sourceUrl} target="_blank">Apply</a></section>}
function Resume(){const[file,setFile]=useState<File|null>(null);const[items,setItems]=useState<any[]>([]);useEffect(()=>{api.get('/resumes').then(r=>setItems(r.data))},[]);async function upload(){if(!file)return;const fd=new FormData();fd.append('resume',file);const{data}=await api.post('/resumes/upload',fd);setItems([data,...items])}return <><h1>Resume Intelligence</h1><input type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/><button onClick={upload}>Analyze</button>{items.map(r=><section className="card"><b>{r.originalName}</b><p>Score: {r.analysis?.resumeScore}</p><p>{r.analysis?.recommendations?.join(' ')}</p></section>)}</>}
function Tracker(){const[apps,setApps]=useState<any[]>([]);useEffect(()=>{api.get('/applications').then(r=>setApps(r.data))},[]);return <><h1>Application Tracker</h1><div className="kanban">{statuses.map(s=><section><h3>{s}</h3>{apps.filter(a=>a.status===s).map(a=><div className="mini"><b>{a.title}</b><p>{a.company}</p></div>)}</section>)}</div></>}
function Profile(){const[p,setP]=useState<any>({skills:[],education:[],preferences:{roles:[]}});useEffect(()=>{api.get('/profile/me').then(r=>setP(r.data||p))},[]);async function save(){await api.put('/profile/me',p);alert('Saved')}return <><h1>Profile</h1><input value={p.fullName||''}onChange={e=>setP({...p,fullName:e.target.value})}placeholder="Full name"/><textarea value={p.bio||''}onChange={e=>setP({...p,bio:e.target.value})}placeholder="Bio"/><input onBlur={e=>setP({...p,skills:e.target.value.split(',').map(name=>({name:name.trim(),proficiencyLevel:3,source:'manual'}))})}placeholder="Skills comma separated"/><button onClick={save}>Save profile</button></>}
createRoot(document.getElementById('root')!).render(<App/>);
