import { Link } from 'react-router-dom';
import { EmptyState, LoadingState } from '../components/LoadingState';
import { MetricCard } from '../components/MetricCard';
import { InternshipCard } from '../components/InternshipCard';
import { api } from '../lib/api';
import { useAsync } from '../hooks/useAsync';
import type { Application, Internship } from '../types';

export function StudentDashboard() { const recs = useAsync<Internship[]>(async () => (await api.get('/recommendations')).data, []); const apps = useAsync<Application[]>(async () => (await api.get('/applications')).data, []); const recommendations = recs.data ?? []; const applications = apps.data ?? []; return <><div className="page-title"><div><h1>Your career at a glance</h1><p className="muted">Recommended roles, pipeline health, and next actions.</p></div><Link className="button" to="/internships">Discover internships</Link></div><div className="cards"><MetricCard label="Top match" value={`${recommendations[0]?.matchScore ?? 0}%`} /><MetricCard label="Applications" value={applications.length} /><MetricCard label="Interviews" value={applications.filter((a) => a.status === 'interview').length} /></div><h2>Recommended internships</h2>{recs.loading ? <LoadingState /> : recommendations.length ? <div className="grid">{recommendations.slice(0, 4).map((i) => <InternshipCard key={i._id} job={i} />)}</div> : <EmptyState title="No recommendations yet"><p>Complete your profile or upload a resume to improve matches.</p></EmptyState>}</>; }
export function RecruiterDashboard() { const jobs = useAsync<Internship[]>(async () => (await api.get('/internships/mine')).data, []); const postings = jobs.data ?? []; return <><div className="page-title"><div><h1>Recruiter dashboard</h1><p className="muted">Manage internship postings and candidate interest.</p></div><Link className="button" to="/internships/new">Create posting</Link></div><div className="cards"><MetricCard label="Open roles" value={postings.length} /><MetricCard label="Remote roles" value={postings.filter((j) => j.workMode === 'remote').length} /><MetricCard label="Total reach" value="Live" /></div><h2>Your postings</h2>{jobs.loading ? <LoadingState /> : postings.length ? <div className="grid">{postings.map((j) => <InternshipCard key={j._id} job={j} recruiter />)}</div> : <EmptyState title="No postings yet"><Link className="button" to="/internships/new">Post your first internship</Link></EmptyState>}</>; }
