import { Link } from 'react-router-dom';
import { EmptyState, LoadingState } from '../components/LoadingState';
import { MetricCard } from '../components/MetricCard';
import { InternshipCard } from '../components/InternshipCard';
import { api } from '../lib/api';
import { useAsync } from '../hooks/useAsync';
import type { Application, Internship } from '../types';

type StudentAnalytics = { totalApplications: number; interviews: number; offers: number; latestResumeScore: number; topSkills: { name: string; confidence?: number }[]; byStatus: Record<string, number> };
type RecruiterAnalytics = { openRoles: number; totalPostings: number; totalApplicants: number; conversionRate: number; byStatus: Record<string, number> };
type AdminOverview = { users: number; students: number; recruiters: number; internships: number; applications: number; resumes: number };

export function StudentDashboard() { const recs = useAsync<Internship[]>(async () => (await api.get('/recommendations')).data, []); const apps = useAsync<Application[]>(async () => (await api.get('/applications')).data, []); const analytics = useAsync<StudentAnalytics>(async () => (await api.get('/analytics/student')).data, []); const recommendations = recs.data ?? []; const applications = apps.data ?? []; return <><div className="page-title"><div><h1>Your career at a glance</h1><p className="muted">AI recommendations, ATS resume scoring, pipeline health, and next actions.</p></div><Link className="button" to="/internships">Discover internships</Link></div><div className="cards"><MetricCard label="Top match" value={`${recommendations[0]?.matchScore ?? 0}%`} /><MetricCard label="ATS score" value={analytics.data?.latestResumeScore ?? 0} /><MetricCard label="Applications" value={analytics.data?.totalApplications ?? applications.length} /><MetricCard label="Interviews" value={analytics.data?.interviews ?? 0} /><MetricCard label="Offers" value={analytics.data?.offers ?? 0} /></div><section className="panel"><h2>Extracted skills</h2><p>{analytics.data?.topSkills?.map((s) => s.name).join(', ') || 'Upload a resume to extract skills.'}</p></section><h2>Recommended internships</h2>{recs.loading ? <LoadingState /> : recommendations.length ? <div className="grid">{recommendations.slice(0, 4).map((i) => <InternshipCard key={i._id} job={i} />)}</div> : <EmptyState title="No recommendations yet"><p>Complete your profile or upload a resume to improve matches.</p></EmptyState>}</>; }
export function RecruiterDashboard() { const jobs = useAsync<Internship[]>(async () => (await api.get('/internships/mine')).data, []); const analytics = useAsync<RecruiterAnalytics>(async () => (await api.get('/analytics/recruiter')).data, []); const postings = jobs.data ?? []; return <><div className="page-title"><div><h1>Recruiter dashboard</h1><p className="muted">Manage internship postings and candidate funnel analytics.</p></div><Link className="button" to="/internships/new">Create posting</Link></div><div className="cards"><MetricCard label="Open roles" value={analytics.data?.openRoles ?? postings.length} /><MetricCard label="Applicants" value={analytics.data?.totalApplicants ?? 0} /><MetricCard label="Conversion" value={`${analytics.data?.conversionRate ?? 0}%`} /></div><h2>Your postings</h2>{jobs.loading ? <LoadingState /> : postings.length ? <div className="grid">{postings.map((j) => <InternshipCard key={j._id} job={j} recruiter />)}</div> : <EmptyState title="No postings yet"><Link className="button" to="/internships/new">Post your first internship</Link></EmptyState>}</>; }
export function AdminDashboard() { const overview = useAsync<AdminOverview>(async () => (await api.get('/admin/overview')).data, []); return <><div className="page-title"><div><h1>Admin dashboard</h1><p className="muted">Platform operations, moderation, and growth metrics.</p></div></div>{overview.loading ? <LoadingState /> : <div className="cards"><MetricCard label="Users" value={overview.data?.users ?? 0} /><MetricCard label="Students" value={overview.data?.students ?? 0} /><MetricCard label="Recruiters" value={overview.data?.recruiters ?? 0} /><MetricCard label="Internships" value={overview.data?.internships ?? 0} /><MetricCard label="Applications" value={overview.data?.applications ?? 0} /><MetricCard label="Resumes" value={overview.data?.resumes ?? 0} /></div>}</>; }
