import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { EmptyState, LoadingState } from '../components/LoadingState';
import { InternshipCard } from '../components/InternshipCard';
import { NoticeBox } from '../components/NoticeBox';
import { api } from '../lib/api';
import type { Internship, Notice } from '../types';
import { money, num, split, workModes } from '../utils/format';

export function InternshipListPage() { const [jobs, setJobs] = useState<Internship[]>([]); const [loading, setLoading] = useState(true); const [q, setQ] = useState(''); const [workMode, setWorkMode] = useState(''); const [skill, setSkill] = useState(''); const params = useMemo(() => ({ q, workMode, skill }), [q, workMode, skill]); useEffect(() => { const id = setTimeout(() => { setLoading(true); api.get('/internships', { params }).then((r) => setJobs(r.data)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(id); }, [params]); return <><div className="page-title"><div><h1>Discover opportunities</h1><p className="muted">Search internships by company, title, work mode, and skill.</p></div></div><div className="filters"><input className="search" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search roles, companies, skills" /><select value={workMode} onChange={(e) => setWorkMode(e.target.value)}><option value="">Any work mode</option>{workModes.map((m) => <option key={m}>{m}</option>)}</select><input value={skill} onChange={(e) => setSkill(e.target.value)} placeholder="Filter skill" /></div>{loading ? <LoadingState /> : jobs.length ? <div className="grid">{jobs.map((j) => <InternshipCard key={j._id} job={j} />)}</div> : <EmptyState title="No internships found"><p>Try a broader search or remove filters.</p></EmptyState>}</>; }

export function InternshipDetailsPage() { const { id } = useParams(); const [job, setJob] = useState<Internship | null>(null); const [notice, setNotice] = useState<Notice>(null); useEffect(() => { api.get(`/internships/${id}`).then((r) => setJob(r.data)).catch((err) => setNotice({ type: 'error', text: err.response?.data?.message ?? 'Internship not found' })); }, [id]); async function apply(status: 'saved' | 'applied') { if (!job) return; try { await api.post('/applications', { internshipId: job._id, company: job.company, title: job.title, sourceUrl: job.sourceUrl, status }); setNotice({ type: 'success', text: status === 'saved' ? 'Saved to tracker' : 'Application tracked' }); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Could not track application' }); } } if (!job && !notice) return <LoadingState />; return <><NoticeBox notice={notice} />{job && <section className="panel detail"><div className="page-title"><div><h1>{job.title}</h1><p>{job.company} · {job.location || 'Remote'} · {job.workMode}</p></div>{job.matchScore !== undefined && <span className="pill">{job.matchScore}% match</span>}</div><p>{job.description}</p><h3>Skills</h3><div className="chips">{job.skills?.map((s) => <span key={s}>{s}</span>)}</div><h3>Requirements</h3><ul>{job.requirements?.map((r) => <li key={r}>{r}</li>)}</ul>{Boolean(job.missingSkills?.length) && <><h3>Skill gaps</h3><div className="chips warning-chips">{job.missingSkills?.map((s) => <span key={s}>{s}</span>)}</div></>}<p><b>Compensation:</b> {money(job.stipendMin, job.stipendMax, job.currency)}</p><div className="actions"><button onClick={() => apply('saved')}>Save</button><button onClick={() => apply('applied')}>Track applied</button>{job.sourceUrl && <a href={job.sourceUrl} target="_blank" rel="noreferrer">External apply</a>}<Link to={`/internships/${job._id}/edit`}>Edit posting</Link></div></section>}</>; }

export function InternshipFormPage() { const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [notice, setNotice] = useState<Notice>(null); const [form, setForm] = useState({ title: '', company: '', description: '', skills: '', requirements: '', location: 'Remote', workMode: 'remote', source: 'recruiter', sourceUrl: 'https://example.com/apply', stipendMin: '', stipendMax: '', currency: 'INR' }); useEffect(() => { if (editing) api.get(`/internships/${id}`).then((r) => { const job: Internship = r.data; setForm({ title: job.title, company: job.company, description: job.description, skills: job.skills?.join(', ') ?? '', requirements: job.requirements?.join(', ') ?? '', location: job.location ?? '', workMode: job.workMode ?? 'remote', source: job.source ?? 'recruiter', sourceUrl: job.sourceUrl ?? '', stipendMin: String(job.stipendMin ?? ''), stipendMax: String(job.stipendMax ?? ''), currency: job.currency ?? 'INR' }); }); }, [editing, id]); async function submit(e: FormEvent) { e.preventDefault(); const payload = { ...form, skills: split(form.skills), requirements: split(form.requirements), stipendMin: num(form.stipendMin), stipendMax: num(form.stipendMax) }; try { const { data } = editing ? await api.put(`/internships/${id}`, payload) : await api.post('/internships', payload); navigate(`/internships/${data._id}`); } catch (err: any) { setNotice({ type: 'error', text: err.response?.data?.message ?? 'Save failed' }); } } return <><h1>{editing ? 'Edit internship' : 'Create internship'}</h1><form className="panel" onSubmit={submit}><NoticeBox notice={notice} />{['title', 'company', 'location', 'sourceUrl', 'skills', 'requirements', 'stipendMin', 'stipendMax', 'currency'].map((k) => <input key={k} value={(form as any)[k]} onChange={(e) => setForm({ ...form, [k]: e.target.value })} placeholder={k} required={['title', 'company', 'sourceUrl'].includes(k)} />)}<select value={form.workMode} onChange={(e) => setForm({ ...form, workMode: e.target.value })}>{workModes.map((m) => <option key={m}>{m}</option>)}</select><textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Description" /><button>{editing ? 'Save changes' : 'Publish internship'}</button></form></>; }
